version: '3'

services:
  php:
    env_file: .env
    build:
      context: ./backend/_/php
    container_name: ${APP_NAME}-php
    restart: always
    volumes:
      - ./backend/_/php/entrypoint.sh:/bin/entrypoint.sh"
      - ${APP_BACKEND_PATH}:/var/www/html/
    networks:
      - app
    expose:
      - 9000
    depends_on:
      - db

  db:
    image: mysql:5.7.32
    container_name: ${APP_NAME}-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app
    ports:
      - 3306:3306

  nodejs:
    env_file: .env
    build:
      context: ./frontend/_/nodejs
    container_name: ${APP_NAME}-nodejs
    restart: "no"
    entrypoint: sh /bin/entrypoint.sh
    volumes:
      - ${APP_FRONTEND_PATH}:/var/www/html
      - ./frontend/_/nodejs/entrypoint.sh:/bin/entrypoint.sh
    networks:
      - app
    ports:
      - 3000:3000

  web:
    image: nginx:1.19.6
    container_name: ${APP_NAME}-nginx
    working_dir: /var/www/html
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/html/
      - ./backend/_/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app
    links:
      - php
    depends_on:
      - php

networks:
  app:
